/** Ajustes exclusivos do leitor Shalom no build. O leitor VERBO não é alterado. */
export function patchShalomReaderSelection(source) {
  let output=source;
  function once(before,after,name) {
    const count=output.split(before).length-1;
    if(count!==1)throw new Error(`Shalom reader selection patch ${name}: expected 1 match, got ${count}`);
    output=output.replace(before,after);
  }
  once("        setDestaqueAtivo(\n            null,\n        );\n\n        setSelecaoDestaque({\n            paginaInicio,","        // No Android, a pesquisa contextual do navegador cobre o rodapé.\n        // Posiciona as ações próximas ao texto selecionado, fora dessa área.\n        const retanguloSelecao = range.getBoundingClientRect();\n        const reservaInferior = window.innerWidth <= 760 ? 165 : 72;\n        const espacoAbaixo = window.innerHeight - retanguloSelecao.bottom;\n        const posicaoDesejada = espacoAbaixo > reservaInferior + 75\n            ? retanguloSelecao.bottom + 12\n            : retanguloSelecao.top - 68;\n        const posicaoFinal = Math.min(\n            Math.max(66, posicaoDesejada),\n            Math.max(66, window.innerHeight - reservaInferior - 56),\n        );\n        document.documentElement.style.setProperty(\n            \"--shalom-selection-toolbar-top\",\n            posicaoFinal + \"px\",\n        );\n\n        setDestaqueAtivo(\n            null,\n        );\n\n        setSelecaoDestaque({\n            paginaInicio,","placement");
  once("                disabled={\n                    modoVisualizacao !==\n                    \"texto\"\n                }","                disabled={\n                    modoVisualizacao !==\n                    \"texto\" ||\n                    Boolean(selecaoDestaque) ||\n                    Boolean(destaqueAtivo)\n                }","dictionary");
  once("<div className=\"book-highlight-toolbar\">","<div\n                        className=\"book-highlight-toolbar\"\n                        role=\"toolbar\"\n                        aria-label=\"Ações do trecho selecionado\"\n                        onPointerDownCapture={(event) => event.preventDefault()}\n                        onMouseDownCapture={(event) => event.preventDefault()}\n                    >","toolbar");
  once("                                <StickyNote\n                                    size={17}\n                                />\n                            </button>","                                <StickyNote\n                                    size={17}\n                                />\n                                <span className=\"shalom-highlight-note-label\">Nota</span>\n                            </button>","note label");
  once("                        {destaqueAtivo && (\n                            <button","                        {selecaoDestaque &&\n                          selecaoDestaque.textoSelecionado.trim().split(/\\s+/).length === 1 && (\n                            <button\n                              type=\"button\"\n                              className=\"shalom-highlight-meaning\"\n                              title=\"Ver significado da palavra\"\n                              onClick={() => {\n                                setPalavraDicionario(selecaoDestaque.textoSelecionado);\n                                setSelecaoDestaque(null);\n                                window.getSelection()?.removeAllRanges();\n                              }}\n                            >\n                              <BookOpen size={15} />\n                              <span>Significado</span>\n                            </button>\n                        )}\n\n                        {destaqueAtivo && (\n                            <button","meaning");
  return output;
}
